### PR TITLE
[Humble] Update the ControllerManger name

### PR DESCRIPTION
**Pull request by AndyZe**
per this MoveIt2 PR:  https://github.com/ros-planning/moveit2/pull/1601

### CODE REVIEW

**Comment by saikishor** [comment]
Thank you for the PR @AndyZe.

**Comment by saikishor** [comment]
Hello @AndyZe!

Could you please update the controller manager name in the .em file as well?

https://github.com/pal-robotics/tiago_moveit_config/blob/6406718ed1848c9332ddfdd42659fed545c9d70c/config/controllers/controllers.yaml.em#L1

**Comment by AndyZe** [comment]
> Could you please update the controller manager name in the .em file as well?

Yep, done

**Review by saikishor — APPROVED** [review]
LGTM

**Pull request merged**
